services:
  ds-proxy:
    networks:
      - frappe_network
    build:
        context: ./frappe-pawville-proxy
        dockerfile: ./Dockerfile
    environment:
      - PORT=6969

      
networks:
  frappe_network:
    driver: bridge